### ISSUE TITLE
Cannot find JDBC Derby Driver with Derby 10.12.1.1

### ISSUE THREAD

**Issue by lastland** [lastland/scala-forklift#16]
With Derby 10.12.1.1:

```
Exception encountered when attempting to run a suite with class name: com.liyaos.forklift.slick.tests.unittests.DerbyMigrationTests *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class org.apache.derby.jdbc.EmbeddedDriver
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at com.zaxxer.hikari.AbstractHikariConfig.setDriverClassName(AbstractHikariConfig.java:366)
[info]   at slick.jdbc.hikaricp.HikariCPJdbcDataSource$$anonfun$forConfig$12.apply(HikariCPJdbcDataSource.scala:28)
[info]   at slick.jdbc.hikaricp.HikariCPJdbcDataSource$$anonfun$forConfig$12.apply(HikariCPJdbcDataSource.scala:28)
[info]   at scala.Option.map(Option.scala:146)
[info]   at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:28)
[info]   ...
```

However, it's fine with Derby 10.11.1.1. Not sure why yet.

**Comment by lastland** [comment]
I mark this as "help wanted" because I can't understand why this happens.
